---

- name: Disable ipv6 1
  command: "sysctl -w net.ipv6.conf.all.disable_ipv6=1"
#  become: yes
#  become_user: "root"
- name: Disable ipv6 2
  command: "sysctl -w net.ipv6.conf.default.disable_ipv6=1"
