- name: Deploy on OpenStack
  hosts: localhost
  gather_facts: false
  vars:
    os: "centos"

  vars_files:
    - vars/common.yml
    - vars/{{ os }}.yml

  tasks:
    - debug: var=user_name
    - name: Create a volume
      os_volume:
        state: present
        size: "{{ volume_size }}"
        display_name: "{{ volume_name }}"

    - name: Deploy a master
      os_server:
        state: present
        name: "{{ master_name }}"
        image: "{{ os_image }}"
        key_name: "{{ key_name }}"
        wait: yes
        flavor: "{{ flavor_name }}"
        auto_floating_ip: yes
        network: "{{ network_name }}"
        security_groups: default,ssh_sg
        meta:
          hostname: "{{ master_name }}.localdomain"
        volumes:
        - "{{ volume_name }}"
      register: master
    - set_fact: master_ip="{{master.server.public_v4}}"
    - name: Wait for SSH on the Instance
      command: >
        ssh -oBatchMode=yes -oStrictHostKeyChecking=no
        {{os}}@{{master.server.public_v4}} true
      register: result
      until: result|success
      retries: 5
      delay: 10
#    - debug:
#        msg: "{{master_ip}}"
    - name: Add master to inventory
      add_host: name=master groups=master_servers
                ansible_ssh_host={{ master.server.public_v4 }}


    - name: Deploy worker nodes
      os_server:
        state: present
        name: "{{ worker_name }}{{ item }}"
        flavor: "{{ flavor_name }}"
        auto_floating_ip: yes
        image: "{{ os_image }}"
        key_name: "{{ key_name }}"
        network: "{{ network_name }}"
        security_groups: default,ssh_sg
        meta:
          hostname: "{{ master_name }}{{ item }}.localdomain"
#      register: workerng{{ item }}
      register: newnodes
      with_sequence:
        count={{ count }}

    - name: Add worker nodes to inventory
      add_host: name={{ item.server.public_v4 }}
                groups=worker_servers
                instance_name={{ item.server.name }}
      with_items: "{{ newnodes.results }}"


- hosts: master_servers
  remote_user: "{{ user_name }}"
#  remote_user: centos
  sudo: yes
  gather_facts: false
  vars:
    os: "centos"
  vars_files:
    - vars/common.yml
    - vars/{{ os }}.yml
  pre_tasks:
    - name: install python
      raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)
      when: os == 'ubuntu'


  roles:
    - update-system
    - ipv6-disable
    - ssh
    - nfs-server
    - master-config
    - scipion-prerequisities
    - scipion



- hosts: worker_servers
  remote_user: "{{ user_name }}"
  sudo: yes
  gather_facts: false
  vars:
    os: "centos"
  vars_files:
    - vars/common.yml
    - vars/{{ os }}.yml
  pre_tasks:
    - name: install python
      raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python)
      when: os == 'ubuntu'

    - name: "Wait for SSH banners"
      local_action: wait_for port=22 host="{{ inventory_hostname }}" search_regex=OpenSSH delay=5
      become: False
  roles:
    - update-system
    - ssh
    - ipv6-disable
    - nfs-client
    - worker-config
    - scipion-prerequisities
