---

- set_fact: master_ip="{{ hostvars['localhost']['master_ip'] }}"
- debug:
    msg: "{{master_ip}}"

- name: Mount opt
  mount:
    name: /opt
    src: "{{ master_ip }}:/opt"
    fstype: nfs
    state: mounted

- name: Mount .config
  mount:
    name: "{{ home_dir }}/.config"
    src: "{{ master_ip }}:{{ home_dir }}/.config"
    fstype: nfs
    state: mounted

- name: Mount ScipionUserData
  mount:
    name: "{{ home_dir }}/ScipionUserData"
    src: "{{ master_ip }}:{{ home_dir }}/ScipionUserData"
    fstype: nfs
    state: mounted
