---

- name: Copy ssh files
  copy:
    src: id_rsa
    dest: "{{ home_dir }}/.ssh/id_rsa"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0600

- name: Copy ssh config
  copy:
    src: config
    dest: "{{ home_dir }}/.ssh/config"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0600

- name: Add authorized key
  authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ lookup('file','authorized_keys') }}"
