---

- name: install scipion prerequisities
  yum: name={{ item }} state=present
  with_items:
   - gcc-c++
   - glibc-headers
   - gcc
   - cmake
   - java-1.8.0-openjdk-devel.x86_64
   - libXft-devel.x86_64
   - openssl-devel.x86_64
   - libXext-devel.x86_64
#   - libxml++.x86_64
   - libquadmath-devel.x86_64
   - libxslt.x86_64
   - openmpi-devel.x86_64
   - gsl-devel.x86_64
   - libX11.x86_64
   - gcc-gfortran.x86_64
