---

- debug: var=user_name
- debug: var=cluster_id
- debug: var=os
- name: Create dir ScipionUserData
  file:
    path: "{{ home_dir }}/ScipionUserData"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Create dir .config
  file:
    path: "{{ home_dir }}/.config"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Create filesystem
  filesystem:
    fstype: xfs
    dev: /dev/vdb

- name: Mount volume
  mount:
    name: /opt
    src: /dev/vdb
    fstype: xfs
    state: mounted

- name: Copy exports
  copy: src=exports.{{os}} dest=/etc/exports owner=root group=root

- name: Restart nfs on ubuntu
  service: name=nfs-kernel-server state=restarted
  when: os == 'ubuntu'

- name: Restart nfs on centos
  service: name=nfs-server state=restarted
  when: os == 'centos'
