---

- name: Create dir ScipionUserData
  file:
    path: "{{ home_dir }}/ScipionUserData"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Create dir .config
  file:
    path: "{{ home_dir }}/.config"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Create filesystem
  filesystem:
    fstype: xfs
    dev: /dev/vdb

- name: Mount volume
  mount:
    name: /opt
    src: /dev/vdb
    fstype: xfs
    state: mounted

- name: Copy exports
  copy: src=exports dest=/etc/exports owner=root group=root

- name: Restart nfs
  service: name=nfs-server state=restarted
